{% set name = "lsstdesc.weaklensingdeblending" %}
{% set version = "0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/LSSTDESC/WeakLensingDeblending/archive/{{ version }}.tar.gz
  sha256: 3c8b0b6be0f21443e5e3ff68e05f678915598f59e0d34b6c6ba01e5be71870d1

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - fitsio
    - galsim
    - numpy
    - astropy
    - lmfit
    - six

test:
  imports:
    - descwl

about:
  home: https://github.com/LSSTDESC/WeakLensingDeblending
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Weak lensing fast simulations and analysis for the LSST DESC
  doc_url: http://weaklensingdeblending.readthedocs.io/

extra:
  recipe-maintainers:
    - beckermr
