{% set name = "lsstdesc.weaklensingdeblending" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/LSSTDESC/WeakLensingDeblending/archive/{{ version }}.tar.gz
  sha256: c5a3f39f9f0aa1785fa15bb9015c99948509ae124a4c77dd8c449d1c67f37ba7

build:
  number: 6
  skip: true  # [win]

outputs:
  - name: {{ name|lower }}
    version: {{ version }}
    script: build_pkg.sh
    requirements:
      host:
        - python
        - pip
      run:
        - python
        - fitsio
        - galsim
        - numpy
        - astropy
        - lmfit
        - six
    test:
      imports:
        - descwl

  - name: {{ name|replace('.', '-')|lower }}
    version: {{ version }}
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("lsstdesc.weaklensingdeblending", exact=True) }}
    test:
      imports:
        - descwl

about:
  home: https://github.com/LSSTDESC/WeakLensingDeblending
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Weak lensing fast simulations and analysis for the LSST DESC
  doc_url: http://weaklensingdeblending.readthedocs.io/

extra:
  recipe-maintainers:
    - beckermr
