{% set name = "lsstdesc.weaklensingdeblending" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/LSSTDESC/WeakLensingDeblending/archive/{{ version }}.tar.gz
  sha256: c5a3f39f9f0aa1785fa15bb9015c99948509ae124a4c77dd8c449d1c67f37ba7

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - fitsio
    - galsim
    - numpy
    - astropy
    - lmfit
    - six

test:
  imports:
    - descwl

about:
  home: https://github.com/LSSTDESC/WeakLensingDeblending
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Weak lensing fast simulations and analysis for the LSST DESC
  doc_url: http://weaklensingdeblending.readthedocs.io/

extra:
  recipe-maintainers:
    - beckermr
