travis:
  secure:
    BINSTAR_TOKEN: IG+l4gkBzoS++AeLj68UCmCdfGZgneoxCryBuUN+HNp+965RcT5HRAjWM32JiOr+gkbVnfm9YsSYyb7s1mvjEm1JW8CJXg11gUT2whkKWY94YWXCFucB124MYawN/sS+6ROB5HuaSCw0Hafik0vQE/FCBvc58JbU9PqK4qp9v3XDr9nsURmV2zVWNq8Rbe2goXE0GDrKJympFhP7LvJAvwdNj/HcPbKtwe/zTBQtxY261G56p41P9Ftr5DQwHWe6Yd8lLE9lcDgTUen2QaWqc+HKgHXn4rqiXqhor5MvMJbKdZQ3ny29OhClsCcXxRh1CmvOdN75uE/t43gzP9o6Jf2l8NNQ/EtOZLv7lkjdaKuQ3njujO75sW67sVqOJg6asDKY7sO/L/V2xESZY+ujRwaLOS9kZRGDSvwH/CJ6s7zIlHSd1eFlTvWmIwGccPyaWL0hb3x12QhxgROrKidO9+XJLEE5+k9qSu2kbtx7n59B4WXmJA5y6airvA4f5ACQLMMuAU4rer3mocOQ03+uvLC4J9HTdTXKcMDAzQ2SraSuCuhEEbfZ71eHfXZL3jh137A/HgHeAAhKUMkFKfLn/HuBYGPfUPeo3jDULRjxmFUqIgI9jHfJK7K0EkNbgqtCJkDUbEhHOCkPty23B5g24i9aX2Bdrm8QuBxKgMkL6Os=
conda_forge_output_validation: true
bot:
  automerge: true
